# Generated by Django 5.0.4 on 2024-04-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('discription', models.TextField()),
                ('composition', models.TimeField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CR', 'Chair'), ('BD', 'Bed'), ('DB', 'Double Bed'), ('SA', 'Sofa'), ('SS', 'Seesam Sofa'), ('SS', 'Seesam Bed')], max_length=2)),
                ('product_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
